print("Simple interest: ")
p = float(input("Enter p: "))
r = float(input("Enter r: "))
t = float(input("Enter t: "))
print(f"Simple interest: {p * r * t / 100}")

print("Compound interest: ")
p = float(input("Enter p: "))
r = float(input("Enter r: "))
t = float(input("Enter t: "))
print(f"Compound interest: {(p * (1 + r/100) ** t) - p : .2f}")
